### PR TITLE
base tk-config with ue

### PR DESCRIPTION
**Pull request by baptisteguidoux**
tk-config-default2 mixed with tk-config-unreal.

### CODE REVIEW

**Comment by lassond** [comment]
I guess you just copied the latest release of `tk-config-default2`?
That's fine. You could have added a remote and branch from their release tag
Or forked their repo

It might have made updates easier in the future.

What do you think?

I will review this no matter what you decide

**Comment by lassond** [comment]
I think that merging to `master` is not the way to go.

The latest Autodesk release is `v1.3.17`, the branch is `release/v1.3.17`

Our first internal release should be something like `v1.3.17.1`

I don't think we need a release branch yet.

So maybe create an `imgspc` branch from their `release/v1.3.17` and merge your changes to `imgspc`

An outstanding question is "how do we remember that we are based on `1.3.17`? Should we add something like a "Release notes" document somewhere?

**Comment by lassond** [comment]
My next question is: from where did you take the `tk-config-unreal` code? 
Their repo?
`master`
some `release` branch?


I will not review Epic's code. If it comes straight from a release in their repo we take it as is. Did you change anything?

**Comment by baptisteguidoux** [comment]
> So maybe create an `imgspc` branch from their `release/v1.3.17` and merge your changes to `imgspc`
> [...]
> An outstanding question is "how do we remember that we are based on `1.3.17`? Should we add something like a "Release notes" document somewhere?

How do you usually proceed when you need to update the config? Do you branch out from the latest branch release each time, or pull the changes? 
If we branch out each time, maybe a `pre-release/v1.3.17.1` branch? This way we know where it comes from and we can work in it. I am not used to the release process so this may sound totally stupid.

> My next question is: from where did you take the tk-config-unreal code?
> Their repo?
> master
> some release branch?
> 
> I will not review Epic's code. If it comes straight from a release in their repo we take it as is. Did you change anything?

I used `master`, which happens to be n the same state as the latest release. Sill a bad habit though.  I did not change anything.

**Comment by baptisteguidoux** [comment]
Closing for https://github.com/imgspc/tk-config-imgspc/pull/2/files

**Pull request closed without merging**
